name: Matrix demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      #fakticky definujeme vsetky rozne verzie, ktore chceme, aby workflow bezal
      #cize tu to budu 2xos a 3xnode, dokopy 2x3=6 roznych konfiguracii!!!
      #tu dokonca spustat node na windows je nezmysel!! alebo nie?
      #ani node12 na ubuntu latest nepobezi....cize treba zvazit aku matrix urobime
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
